src/components/ArticleList.vue
src/components/ArticleMeta.vue
src/components/TheHeader.vue
src/views/Article.vue
src/views/ArticleEdit.vue
src/views/Home.vue
src/views/Login.vue
src/views/Profile.vue
src/views/Register.vue
src/views/Settings.vue

Using vuex state and getters helpers

---

package-lock.json
package.json
src/common/date.filter.js
yarn.lock

reduce package size by replacing moment with date-fns
closes #9

replace moment by date-fns

---

src/views/Login.vue
src/views/Register.vue

prevent auth form from reloading the page

---

LICENSE

chore: add license #20

---

src/components/ArticleActions.vue
src/components/ArticleMeta.vue
src/views/Profile.vue

feat: make article page follow btn working

---

src/components/ArticleActions.vue
src/components/ArticleMeta.vue

Navigate to login page when user (didn't login) click to follow button, favorite button

Add navigate to follow, favorite button when user didn't login

---

src/components/ArticleList.vue

Change RwvArticlePreview and VPagination to self closing.
Closes #66

Make components self closing

---

src/common/jwt.service.js
src/components/ArticleActions.vue

The functions getToken, saveToken and destroyToken can now be imported like import { getToken, saveToken, destroyToken } from ".../jwt.service" but also the full object can be imported like import JwtService from ".../jwt.service".
#70

Export default jwt.service

---

src/components/TheFooter.vue

New line between `<template></template>` and `<script></script>`
Please review this and let me know if something else is neede.

Added a new line between components.

---

src/components/ArticleActions.vue

Refactored methods calls in ArticleActions. fixes #75

Refactored methods calls in ArticleActions

---

src/components/ArticleActions.vue

Refactor delete article method to use asyn await and a try catch block

---

src/components/ArticleList.vue

Converting imports to use relative paths

---

src/components/ArticleActions.vue

TODO: enhance #71 
1. Wrapped free texts by ```<span>``` tags in ```<template>```

feat(articleActions): Wrap free texts into <span> tag

---

src/components/TheFooter.vue

Rename component name in TheFooter

---

public/index.html

fixes #104 
Added Symbol polyfill check
cc @JonDReese

add polyfill service

---

src/components/TagList.vue
src/components/VArticlePreview.vue

Refactored article preview component

Refactor article preview

---

README.md

change readme to use subheadings and add a FAQ area which handles service worker for now (fixes #112)
@mr-lanholmes This might be covering your issue you have created here: https://github.com/gothinkster/vue-realworld-example-app/issues/112

docs: create faq, update formatting

---

README.md

- will fix #161 
- Add answer about the functional Vue.js 3 proposal
@afattahi54, I pinged you here to approve the changes.

Add more content to FAQ

---

package.json
yarn.lock

fix #189 with cross-env for all environments

chore(189): use cross-env

---

src/components/VTag.vue

VTag: Uninline content

---

src/components/CommentEditor.vue

style: use PascalCase for imported component in CommentEditor.vue

---

tests/unit/components/VTag.spec.js

This is linked to #195
My suggestion for a lose coupled test.

test: Add spec for VTag that router is called

---

src/components/VTag.vue

Updating `VTag` component, Use computed property for router link

Use computed property for router link

---

src/components/ArticleMeta.vue
src/components/Comment.vue
src/views/ArticleEdit.vue
src/views/Login.vue
src/views/Register.vue

use directive shorthand @ instead of v-on

---

README.md

update readme with editor config instructions
